# in data_transformation/models/sources.yml
sources:
  - name: jobads
    schema: staging
    tables:
      - name: hits
        meta: # This metadata specifies the corresponding Dagster asset for this dbt source.
          dagster:
            asset_key: ["dlt_jobads_source_get_hits"]
